server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodatabase?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
